# example profiles.yml file
redshift_profile:
  target: dev
  outputs:
    dev:
      type: redshift
      host: localhost
      user: tharvey
      password: {{ env_var('REDSHIFT_PASSWORD') }}
      port: 55091
      dbname: sandbox_tharvey
      schema: public
      threads: 4

sqlite_profile:
  # See https://github.com/codeforkjeff/dbt-sqlite
  target: dev
  outputs:
    dev:
      type: sqlite

snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}

      # User/password auth
      user: {{ env_var('SNOWFLAKE_USER') }}
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}

      role: {{ env_var('SNOWFLAKE_ROLE') }}
      database: {{ env_var('SNOWFLAKE_DATABASE') }}
      warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE') }}
