name: codecov

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  run-tests:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Test Coverage
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Install python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install .['dev']
      - name: Generate coverage report
        run: pytest --cov=migro --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
